server:
  port: 1000
spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_local?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
#  dubbo的服务既可以是消费者也可以值提供者，消费者不需要配置protocol这个项目，其他的都一样
dubbo:
  application:
    name: dubbo_provider #dubbo的引用名称，必须配置，是放在注册中心的标志
  registry: #注册中心的地址和协议
    address: zookeeper://192.168.226.128:2181
    protocol: zookeeper
    version: 1.0.0
    timeout: 30000
  protocol: #dubbo连接的协议名和端口
    name: dubbo
    port: 20880
  config-center:
    timeout: 30000 #连接超时的设置
  consumer:
    check: false
app:
  id: testwdg
apollo:
  meta: http://106.54.227.205:8080
  #cluster: myCluster
  cacheDir: D:\\opt\\testDir
  bootstrap:
    enable: true
    namespaces: application

env: DEV
